### ISSUE TITLE
EKS Deploy fails with Helm 

### ISSUE THREAD

**Issue by vishaal314** [trieb-work/helm-charts#1]
Description : trying to deploy the saleor with Helm , saleor-core .

Environment  : AWS EKS , kubectl , helm , django , Linux  AMI ec2

Steps to reproduce : 
git clone code from - https://github.com/trieb-work/helm-charts.git
navigate to saleor-Helm folder 
https://github.com/trieb-work/helm-charts  ----> try "helm repo add trieb.work https://trieb-work.github.io/helm-charts/" 
                                                                                      "helm install saleor trieb.work/saleor-helm" 

There is no deployment from helm as no mssg displayed .
Expected result : after Helm Install the saleor application should be available .

![image](https://user-images.githubusercontent.com/37283997/129455755-8e79ab31-a9a7-4065-b602-d951f84387a1.png)
![error](https://user-images.githubusercontent.com/37283997/129455767-94965bb6-810e-4afa-92ec-07ba0c8bf19a.jpg)

**Comment by JannikZed** [comment]
Hi @vishaal314 - first of all, you don't need to clone the repo. Just adding it with `helm repo add` is enough :) 

secondly, I just released a new version of the chart, that is including default values for all the S3 settings. Try to update your chart repo with `helm repo update` and try to install the chart again.

**Comment by vishaal314** [comment]
Hi @JannikZed  -
 Thanks for your update but result is not changing . 
 I have attached the screen shot for your information , please let me know if any detail is required .
I want to install saleor-core only  with helm chart .
![errr](https://user-images.githubusercontent.com/37283997/129580579-70191622-d00a-4bb9-8b7b-6ead18f11263.JPG)

**Comment by JannikZed** [comment]
@vishaal314 please share the container logs of the API and the docker image, that was deployed :) 
I think, that saleor is blocking this request, as 127.0.0.1 is not allowed to access it. Could you try to overwrite the environment variables ALLOWED_HOSTS and ALLOWED_CLIENT_HOSTS with `127.0.0.1` ?

**Comment by vishaal314** [comment]
@JannikZed I used helm repo to deploy saleor  as shown in attached pic 
![image](https://user-images.githubusercontent.com/37283997/131538830-d5320ec8-fbb8-46f1-8a09-cf15c19a10a0.png)

please let me know , where can i overwrite environment variables  ? 

I followed these steps below 

![image](https://user-images.githubusercontent.com/37283997/131539151-db646ce2-0658-4623-8638-ff503d049914.png)
